### ISSUE TITLE
An Internal Error occured !

### ISSUE THREAD

**Issue by LeLuniXx** [lijinhong11/BossShopPro#1]
Hallo. Ich habe das Bosshop Plugin jetzt ausgetauscht aber leider gibt das Plugin einen Fehler aus wenn ich im Shop Ordner den Menu.yml Shop entferne. Wenn ich die yml wieder hineinlege funktionierts sobald ich diese wieder entferne und reloade kommt der Fehler.

**Comment by lijinhong11** [comment]
Schließlich handelt es sich um eine modifizierte Version. Ich schlage vor, dass Sie den generierten Ordner löschen und die Generierung neu starten. Sollte das Problem weiterhin bestehen, senden Sie mir bitte den Fehlerbericht

**Comment by LeLuniXx** [comment]
Ich habe mehrfach den Ordner entfernt und den Server neugestartet. 
Dieser Fehler kommt wenn ich /bs reload eingebe.

org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v3.1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.2.jar:git-Paper-141]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-141]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2292) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2246) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-141]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-141]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.black_ixx.bossshop.settings.SettingsProperty.containsValueAny(Object)" because the return value of "org.black_ixx.bossshop.settings.Settings.getProperty(int)" is null
        at org.black_ixx.bossshop.managers.ClassManager.setupDependentClasses(ClassManager.java:131) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.BossShop.reloadPlugin(BossShop.java:146) ~[BossShopPro.jar:?]
        at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:28) ~[BossShopPro.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by lijinhong11** [comment]
In 3.1.7 zu reparieren
